[package]
name = "wasi-authz-testkit"
publish = false
description = "Conformance fixtures for wasi-authz policy decision providers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
thiserror.workspace = true
wasi-authz-client = { path = "../wasi-authz-client", version = "=0.1.0-alpha.4" }
wasi-authz-contract.workspace = true

[lints]
workspace = true
