[package]
name = "wasi-authz-spicedb"
description = "SpiceDB CheckPermission decision provider for wasi-authz"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
base64.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
wasi-authz-client.workspace = true
wasi-authz-contract.workspace = true

[dev-dependencies]
wasi-authz-testkit = { path = "../wasi-authz-testkit", version = "=0.1.0-rc.4" }

[lints]
workspace = true
