//! Typed Leptos request context and `server_fn` authorization layers.
//!
//! Layers inspect canonical trusted headers only. They never collect or alter
//! server-function request bodies.

#![deny(rustdoc::broken_intra_doc_links)]

use std::fmt;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use axum_core::body::Body as AxumBody;
use futures::lock::Mutex;
use http::header::{AUTHORIZATION, WWW_AUTHENTICATE};
use http::request::Parts;
use http::{HeaderMap, Request, Response, StatusCode};
use leptos::prelude::{provide_context, use_context};
use server_fn::ServerFnError;
use server_fn::error::ServerFnErrorErr;
use server_fn::middleware::{BoxedService, Layer, Service};
use thiserror::Error;
use wasi_authz_client::DecisionProvider;
use wasi_authz_contract::{
    AccessEvaluation, Action, Consistency, ContextV1, ContractError, DecisionMetadataV1,
    DecisionResponseV1, Resource, SubjectV1,
};
use wasi_authz_http::subject_from_auth_context;
use wasi_http_metadata::parse_auth_context;
pub use wasi_http_metadata::{AuthContextV1, AuthStateV1, PrincipalV1, VerifiedAuthContext};

/// Request type generated by Axum-compatible Leptos server functions.
pub type ServerFnRequest = Request<AxumBody>;
/// Response type generated by Axum-compatible Leptos server functions.
pub type ServerFnResponse = Response<AxumBody>;

type ResponseStatusCallback = dyn Fn(StatusCode, &HeaderMap) + Send + Sync;

/// Failure while reading trusted authentication metadata from Leptos context.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
#[non_exhaustive]
pub enum AuthContextError {
    /// Standard request parts were not installed by the HTTP integration.
    #[error("standard request parts are unavailable")]
    MissingRequestParts,
    /// No authentication context was installed in the current reactive owner.
    #[error("authentication context is unavailable")]
    MissingContext,
    /// Trusted metadata was absent, malformed, duplicated, or bypassed.
    #[error("trusted authentication boundary is invalid")]
    InvalidBoundary,
}

/// Cloneable adapter for applying authorization failures to an HTTP response.
///
/// The callback receives only a status and library-created safe headers. This
/// keeps the companion crate independent from any particular Leptos HTTP
/// runtime while allowing an application to adapt its response-options type.
#[derive(Clone)]
pub struct ResponseStatusSink {
    callback: Arc<ResponseStatusCallback>,
}

impl ResponseStatusSink {
    /// Creates a response adapter from a synchronous callback.
    pub fn new<F>(callback: F) -> Self
    where
        F: Fn(StatusCode, &HeaderMap) + Send + Sync + 'static,
    {
        Self {
            callback: Arc::new(callback),
        }
    }

    fn apply(&self, status: StatusCode, headers: &HeaderMap) {
        (self.callback)(status, headers);
    }
}

impl fmt::Debug for ResponseStatusSink {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ResponseStatusSink")
            .finish_non_exhaustive()
    }
}

/// Installs a response-status adapter in the current Leptos reactive owner.
pub fn provide_response_status_sink(sink: ResponseStatusSink) {
    provide_context(sink);
}

/// Typed trusted authorization context available to Leptos server code.
#[derive(Clone)]
pub struct LeptosAuthzContext {
    authentication: AuthContextV1,
    subject: SubjectV1,
}

impl fmt::Debug for LeptosAuthzContext {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LeptosAuthzContext")
            .field("authentication", &"[REDACTED]")
            .field("authenticated", &self.authentication.principal().is_some())
            .field("subject", &"[REDACTED]")
            .finish()
    }
}

impl LeptosAuthzContext {
    /// Parses exactly one canonical authentication header and verifies the
    /// immutable service binding.
    ///
    /// # Errors
    ///
    /// Returns [`LeptosAuthzError::InvalidBoundary`] for missing, duplicate,
    /// malformed, or cross-service metadata.
    pub fn from_headers(
        headers: &HeaderMap,
        expected_service_id: &str,
    ) -> Result<Self, LeptosAuthzError> {
        Self::from_headers_at(headers, expected_service_id, system_unix_time())
    }

    /// Parses trusted headers using an injected Unix time for deterministic
    /// expiration checks.
    ///
    /// # Errors
    ///
    /// Returns a boundary or unauthenticated error for invalid context.
    pub fn from_headers_at(
        headers: &HeaderMap,
        expected_service_id: &str,
        now: u64,
    ) -> Result<Self, LeptosAuthzError> {
        Self::from_headers_at_for_audiences(
            headers,
            expected_service_id,
            &[expected_service_id.to_owned()],
            now,
        )
    }

    fn from_headers_at_for_audiences(
        headers: &HeaderMap,
        expected_service_id: &str,
        expected_audiences: &[String],
        now: u64,
    ) -> Result<Self, LeptosAuthzError> {
        if headers.contains_key(AUTHORIZATION) {
            return Err(LeptosAuthzError::InvalidBoundary);
        }
        let authentication =
            parse_auth_context(headers).map_err(|_| LeptosAuthzError::InvalidBoundary)?;
        if authentication.service_id() != expected_service_id {
            return Err(LeptosAuthzError::InvalidBoundary);
        }
        if !expected_audiences.iter().any(|expected| {
            authentication
                .audiences()
                .iter()
                .any(|actual| actual == expected)
        }) {
            return Err(LeptosAuthzError::Unauthenticated);
        }
        if authentication
            .principal()
            .and_then(PrincipalV1::expires_at)
            .is_some_and(|expires_at| expires_at <= now)
        {
            return Err(LeptosAuthzError::Unauthenticated);
        }
        let subject = subject_from_auth_context(&authentication, expected_service_id)
            .map_err(|_| LeptosAuthzError::InvalidBoundary)?;
        Ok(Self {
            authentication,
            subject,
        })
    }

    fn from_verified_at_for_audiences(
        verified: &VerifiedAuthContext,
        expected_service_id: &str,
        expected_audiences: &[String],
        now: u64,
    ) -> Result<Self, LeptosAuthzError> {
        let authentication = verified.context().clone();
        if authentication.service_id() != expected_service_id {
            return Err(LeptosAuthzError::InvalidBoundary);
        }
        if !expected_audiences.iter().any(|expected| {
            authentication
                .audiences()
                .iter()
                .any(|actual| actual == expected)
        }) {
            return Err(LeptosAuthzError::Unauthenticated);
        }
        if authentication
            .principal()
            .and_then(PrincipalV1::expires_at)
            .is_some_and(|expires_at| expires_at <= now)
        {
            return Err(LeptosAuthzError::Unauthenticated);
        }
        let subject = subject_from_auth_context(&authentication, expected_service_id)
            .map_err(|_| LeptosAuthzError::InvalidBoundary)?;
        Ok(Self {
            authentication,
            subject,
        })
    }

    /// Returns the canonical authentication envelope.
    pub fn authentication(&self) -> &AuthContextV1 {
        &self.authentication
    }

    /// Returns the explicit anonymous or authenticated authorization subject.
    pub fn subject(&self) -> &SubjectV1 {
        &self.subject
    }

    /// Returns the authenticated principal or a 401-class error.
    ///
    /// # Errors
    ///
    /// Returns [`LeptosAuthzError::Unauthenticated`] for anonymous context.
    pub fn require_principal(&self) -> Result<&PrincipalV1, LeptosAuthzError> {
        self.authentication
            .principal()
            .ok_or(LeptosAuthzError::Unauthenticated)
    }

    /// Enforces one provider decision and returns only an explicit allow.
    ///
    /// # Errors
    ///
    /// Returns 401/403-class errors for a valid deny and a 503-class error for
    /// provider or indeterminate failures.
    pub async fn authorize<P>(
        &self,
        provider: &P,
        action: Action,
        resource: Resource,
    ) -> Result<DecisionResponseV1, LeptosAuthzError>
    where
        P: DecisionProvider,
    {
        let evaluation = AccessEvaluation::new(self.subject.clone(), action, resource);
        match provider.evaluate(&evaluation).await {
            Ok(decision) if decision.is_allowed() => Ok(decision),
            Ok(_) if self.subject.is_authenticated() => Err(LeptosAuthzError::Forbidden),
            Ok(_) => Err(LeptosAuthzError::Unauthenticated),
            Err(_) => Err(LeptosAuthzError::ProviderUnavailable),
        }
    }
}

/// Parses a service-bound typed context from explicit headers.
///
/// # Errors
///
/// Returns [`LeptosAuthzError::InvalidBoundary`] for invalid trusted metadata.
pub fn parse_authz_context_for_service(
    headers: &HeaderMap,
    expected_service_id: &str,
) -> Result<LeptosAuthzContext, LeptosAuthzError> {
    LeptosAuthzContext::from_headers(headers, expected_service_id)
}

/// Reads the verified request extension and installs raw authentication
/// context in the current reactive owner.
///
/// # Errors
///
/// Returns [`AuthContextError`] when standard request context or the verified
/// authentication boundary is missing.
pub fn provide_auth_context() -> Result<AuthContextV1, AuthContextError> {
    let parts = use_context::<Parts>().ok_or(AuthContextError::MissingRequestParts)?;
    let context = parts
        .extensions
        .get::<VerifiedAuthContext>()
        .ok_or(AuthContextError::InvalidBoundary)?
        .context()
        .clone();
    provide_context(context.clone());
    Ok(context)
}

/// Returns raw authentication context from the current Leptos owner.
///
/// # Errors
///
/// Returns [`AuthContextError::MissingContext`] when context is missing.
pub fn current_auth_context() -> Result<AuthContextV1, AuthContextError> {
    use_context().ok_or(AuthContextError::MissingContext)
}

/// Returns the verified service-bound context installed by an authorization
/// layer in the current Leptos owner.
///
/// # Errors
///
/// Returns [`AuthContextError::MissingContext`] when no authorization layer
/// installed a typed context.
pub fn current_authz_context() -> Result<LeptosAuthzContext, AuthContextError> {
    use_context().ok_or(AuthContextError::MissingContext)
}

/// Returns an owned authenticated principal from current context.
///
/// # Errors
///
/// Returns [`ServerFnError`] and sets status 401 for anonymous or expired
/// identity, and 503 when context is missing.
pub fn require_principal() -> Result<PrincipalV1, ServerFnError> {
    let context = current_authz_context().map_err(auth_context_server_error)?;
    let principal =
        context.authentication.principal().cloned().ok_or_else(|| {
            server_fn_error(StatusCode::UNAUTHORIZED, "authentication is required")
        })?;
    if principal
        .expires_at()
        .is_some_and(|expires_at| expires_at <= system_unix_time())
    {
        return Err(server_fn_error(
            StatusCode::UNAUTHORIZED,
            "authentication is expired",
        ));
    }
    Ok(principal)
}

/// Enforces a prepared typed evaluation and returns decision metadata.
///
/// Resource loading and typed server-function argument deserialization should
/// occur before this call. No static pre-body resource authorization is
/// performed by the integration crate.
///
/// # Errors
///
/// Returns [`ServerFnError`] with 401/403 for valid denials and 503 for
/// provider or indeterminate failures.
pub async fn authorize<P>(
    provider: &P,
    evaluation: AccessEvaluation,
) -> Result<DecisionMetadataV1, ServerFnError>
where
    P: DecisionProvider,
{
    let context = current_authz_context().map_err(auth_context_server_error)?;
    let canonical_subject =
        subject_from_auth_context(&context.authentication, context.authentication.service_id())
            .map_err(|_| {
                server_fn_error(
                    StatusCode::SERVICE_UNAVAILABLE,
                    "trusted authentication boundary is invalid",
                )
            })?;
    if canonical_subject != *evaluation.subject() {
        return Err(server_fn_error(
            StatusCode::SERVICE_UNAVAILABLE,
            "authorization subject does not match trusted identity",
        ));
    }
    if context
        .authentication
        .principal()
        .and_then(PrincipalV1::expires_at)
        .is_some_and(|expires_at| expires_at <= system_unix_time())
    {
        return Err(server_fn_error(
            StatusCode::UNAUTHORIZED,
            "authentication is expired",
        ));
    }
    match provider.evaluate(&evaluation).await {
        Ok(decision) if decision.is_allowed() => Ok(decision.metadata().clone()),
        Ok(_) if evaluation.subject().is_authenticated() => Err(server_fn_error(
            StatusCode::FORBIDDEN,
            "authorization was denied",
        )),
        Ok(_) => Err(server_fn_error(
            StatusCode::UNAUTHORIZED,
            "authentication is required",
        )),
        Err(_) => Err(server_fn_error(
            StatusCode::SERVICE_UNAVAILABLE,
            "authorization provider is unavailable",
        )),
    }
}

/// Metadata returned by a Cedar-first hybrid authorization decision.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub struct HybridDecisionMetadata {
    cedar: DecisionMetadataV1,
    relationship: DecisionMetadataV1,
}

impl HybridDecisionMetadata {
    /// Returns metadata from the embedded Cedar decision.
    #[must_use]
    pub fn cedar(&self) -> &DecisionMetadataV1 {
        &self.cedar
    }

    /// Returns metadata from the relationship authorization decision.
    #[must_use]
    pub fn relationship(&self) -> &DecisionMetadataV1 {
        &self.relationship
    }
}

/// Enforces Cedar first and evaluates relationships only after Cedar permits.
///
/// This helper guarantees that an RBAC or ABAC denial never causes a remote
/// relationship-provider call.
///
/// # Errors
///
/// Returns the same safe 401, 403, or 503 [`ServerFnError`] mapping as
/// [`authorize`].
pub async fn authorize_hybrid_current<C, S>(
    cedar: &C,
    relationship: &S,
    evaluation: AccessEvaluation,
) -> Result<HybridDecisionMetadata, ServerFnError>
where
    C: DecisionProvider,
    S: DecisionProvider,
{
    let cedar = authorize(cedar, evaluation.clone()).await?;
    let relationship = authorize(relationship, evaluation).await?;
    Ok(HybridDecisionMetadata {
        cedar,
        relationship,
    })
}

/// Authorizes a domain action and resource for the verified current subject.
///
/// Call this after server-function arguments have been deserialized and any
/// resource required to construct the typed policy input has been loaded.
///
/// # Errors
///
/// Returns [`ServerFnError`] with 401/403 for valid denials and 503 for a
/// missing context, subject mismatch, or unavailable provider.
pub async fn authorize_current<P>(
    provider: &P,
    action: Action,
    resource: Resource,
) -> Result<DecisionMetadataV1, ServerFnError>
where
    P: DecisionProvider,
{
    let context = current_authz_context().map_err(auth_context_server_error)?;
    authorize(
        provider,
        AccessEvaluation::new(context.subject.clone(), action, resource),
    )
    .await
}

/// Authorizes the current subject with an explicit relationship consistency
/// requirement.
///
/// Use this for relationship-sensitive reads and mutations after the resource
/// has been loaded. Mutations should request fully-consistent evaluation or
/// carry the resource's previously returned consistency token.
///
/// # Errors
///
/// Returns [`ServerFnError`] with 401/403 for valid denials and 503 for a
/// missing context, subject mismatch, or unavailable provider.
pub async fn authorize_current_relationship<P>(
    provider: &P,
    action: Action,
    resource: Resource,
    consistency: Consistency,
) -> Result<DecisionMetadataV1, ServerFnError>
where
    P: DecisionProvider,
{
    let context = current_authz_context().map_err(auth_context_server_error)?;
    let evaluation = AccessEvaluation::new(context.subject.clone(), action, resource)
        .with_context(ContextV1::new().with_consistency(consistency));
    authorize(provider, evaluation).await
}

/// Authorizes the current subject with Cedar before relationship evaluation.
///
/// Call this after typed server-function arguments are deserialized and the
/// resource has been loaded. A Cedar denial or provider failure short-circuits
/// without invoking the relationship provider.
///
/// # Errors
///
/// Returns [`ServerFnError`] with 401/403 for valid denials and 503 for a
/// missing context, subject mismatch, or unavailable provider.
pub async fn authorize_current_hybrid<C, S>(
    cedar: &C,
    relationship: &S,
    action: Action,
    resource: Resource,
) -> Result<HybridDecisionMetadata, ServerFnError>
where
    C: DecisionProvider,
    S: DecisionProvider,
{
    let context = current_authz_context().map_err(auth_context_server_error)?;
    authorize_hybrid_current(
        cedar,
        relationship,
        AccessEvaluation::new(context.subject.clone(), action, resource),
    )
    .await
}

/// Authorizes the current subject with Cedar before a consistency-sensitive
/// relationship evaluation.
///
/// Cedar receives the domain authorization input without provider-specific
/// relationship consistency. The relationship provider runs only after Cedar
/// permits and receives the supplied consistency requirement.
///
/// # Errors
///
/// Returns [`ServerFnError`] with 401/403 for valid denials and 503 for a
/// missing context, subject mismatch, or unavailable provider.
pub async fn authorize_current_hybrid_with_consistency<C, S>(
    cedar: &C,
    relationship: &S,
    action: Action,
    resource: Resource,
    relationship_consistency: Consistency,
) -> Result<HybridDecisionMetadata, ServerFnError>
where
    C: DecisionProvider,
    S: DecisionProvider,
{
    let context = current_authz_context().map_err(auth_context_server_error)?;
    let cedar_evaluation =
        AccessEvaluation::new(context.subject.clone(), action.clone(), resource.clone());
    let cedar = authorize(cedar, cedar_evaluation).await?;
    let relationship_evaluation = AccessEvaluation::new(context.subject, action, resource)
        .with_context(ContextV1::new().with_consistency(relationship_consistency));
    let relationship = authorize(relationship, relationship_evaluation).await?;
    Ok(HybridDecisionMetadata {
        cedar,
        relationship,
    })
}

/// Leptos authorization failure with stable HTTP mapping.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
#[non_exhaustive]
pub enum LeptosAuthzError {
    /// No typed context was installed in the current Leptos owner.
    #[error("authorization context is missing")]
    MissingContext,
    /// Trusted authentication metadata was absent, malformed, or cross-service.
    #[error("invalid trusted authentication boundary")]
    InvalidBoundary,
    /// Authentication is required.
    #[error("authentication is required")]
    Unauthenticated,
    /// The authenticated principal is not authorized.
    #[error("authorization was denied")]
    Forbidden,
    /// No trustworthy policy decision was available.
    #[error("authorization provider is unavailable")]
    ProviderUnavailable,
    /// Layer configuration did not fit the bounded contract.
    #[error("invalid authorization layer configuration")]
    InvalidConfiguration,
}

impl LeptosAuthzError {
    /// Returns the stable HTTP status for the failure class.
    pub fn status(self) -> StatusCode {
        match self {
            Self::Unauthenticated => StatusCode::UNAUTHORIZED,
            Self::Forbidden => StatusCode::FORBIDDEN,
            Self::MissingContext
            | Self::InvalidBoundary
            | Self::ProviderUnavailable
            | Self::InvalidConfiguration => StatusCode::SERVICE_UNAVAILABLE,
        }
    }
}

/// Server-function middleware requiring an authenticated principal.
#[derive(Clone, Debug)]
pub struct RequireAuthLayer {
    service_id: Arc<str>,
    expected_audiences: Arc<[String]>,
    now: fn() -> u64,
}

impl RequireAuthLayer {
    /// Validates and constructs the layer.
    ///
    /// # Errors
    ///
    /// Returns [`LeptosAuthzError::InvalidConfiguration`] for an invalid
    /// service identifier.
    pub fn new(service_id: impl Into<String>) -> Result<Self, LeptosAuthzError> {
        let service_id = validated_service_id(service_id.into())?;
        let expected_audiences = vec![service_id.to_string()].into();
        Ok(Self {
            service_id,
            expected_audiences,
            now: system_unix_time,
        })
    }

    /// Replaces the default service-name audience with accepted OAuth
    /// audiences.
    ///
    /// A request is accepted when its trusted configured audience set
    /// intersects this set. The immutable terminal service ID is checked
    /// separately.
    ///
    /// # Errors
    ///
    /// Returns [`LeptosAuthzError::InvalidConfiguration`] for an empty,
    /// oversized, or malformed audience set.
    pub fn with_expected_audiences<I, S>(mut self, audiences: I) -> Result<Self, LeptosAuthzError>
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        self.expected_audiences = validated_expected_audiences(audiences)?;
        Ok(self)
    }

    /// Injects a deterministic Unix-time source.
    pub fn with_time_source(mut self, now: fn() -> u64) -> Self {
        self.now = now;
        self
    }
}

impl Layer<ServerFnRequest, ServerFnResponse> for RequireAuthLayer {
    fn layer(
        &self,
        inner: BoxedService<ServerFnRequest, ServerFnResponse>,
    ) -> BoxedService<ServerFnRequest, ServerFnResponse> {
        let serializer = inner.ser;
        BoxedService::new(
            serializer,
            RequireAuthService {
                inner: Arc::new(Mutex::new(inner)),
                service_id: Arc::clone(&self.service_id),
                expected_audiences: Arc::clone(&self.expected_audiences),
                now: self.now,
            },
        )
    }
}

struct RequireAuthService {
    inner: SharedService,
    service_id: Arc<str>,
    expected_audiences: Arc<[String]>,
    now: fn() -> u64,
}

impl Service<ServerFnRequest, ServerFnResponse> for RequireAuthService {
    fn run(
        &mut self,
        request: ServerFnRequest,
        _serialize_error: fn(ServerFnErrorErr) -> bytes::Bytes,
    ) -> ServerFnFuture {
        let context = match verified_context_from_request(
            &request,
            &self.service_id,
            &self.expected_audiences,
            (self.now)(),
        ) {
            Ok(context) => context,
            Err(error) => return response_future(error.status()),
        };
        if context.require_principal().is_err() {
            return response_future(StatusCode::UNAUTHORIZED);
        }
        provide_context(context.authentication.clone());
        provide_context(context);
        run_inner(Arc::clone(&self.inner), request)
    }
}

/// Server-function middleware requiring every configured OAuth scope.
#[derive(Clone, Debug)]
pub struct RequireScopesLayer {
    service_id: Arc<str>,
    expected_audiences: Arc<[String]>,
    scopes: Arc<[String]>,
    now: fn() -> u64,
}

impl RequireScopesLayer {
    /// Validates and constructs a canonical scope requirement.
    ///
    /// # Errors
    ///
    /// Returns [`LeptosAuthzError::InvalidConfiguration`] for empty, invalid,
    /// or excessive requirements.
    pub fn new<I, S>(service_id: impl Into<String>, scopes: I) -> Result<Self, LeptosAuthzError>
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        let mut scopes = scopes.into_iter().map(Into::into).collect::<Vec<_>>();
        if scopes.is_empty()
            || scopes.len() > 32
            || scopes
                .iter()
                .any(|scope| wasi_authz_contract::ScopeV1::new(scope).is_err())
        {
            return Err(LeptosAuthzError::InvalidConfiguration);
        }
        scopes.sort_unstable();
        scopes.dedup();
        let service_id = validated_service_id(service_id.into())?;
        let expected_audiences = vec![service_id.to_string()].into();
        Ok(Self {
            service_id,
            expected_audiences,
            scopes: scopes.into(),
            now: system_unix_time,
        })
    }

    /// Replaces the default service-name audience with accepted OAuth
    /// audiences.
    ///
    /// A request is accepted when its trusted configured audience set
    /// intersects this set. The immutable terminal service ID is checked
    /// separately.
    ///
    /// # Errors
    ///
    /// Returns [`LeptosAuthzError::InvalidConfiguration`] for an empty,
    /// oversized, or malformed audience set.
    pub fn with_expected_audiences<I, S>(mut self, audiences: I) -> Result<Self, LeptosAuthzError>
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        self.expected_audiences = validated_expected_audiences(audiences)?;
        Ok(self)
    }

    /// Injects a deterministic Unix-time source.
    pub fn with_time_source(mut self, now: fn() -> u64) -> Self {
        self.now = now;
        self
    }
}

impl Layer<ServerFnRequest, ServerFnResponse> for RequireScopesLayer {
    fn layer(
        &self,
        inner: BoxedService<ServerFnRequest, ServerFnResponse>,
    ) -> BoxedService<ServerFnRequest, ServerFnResponse> {
        let serializer = inner.ser;
        BoxedService::new(
            serializer,
            RequireScopesService {
                inner: Arc::new(Mutex::new(inner)),
                service_id: Arc::clone(&self.service_id),
                expected_audiences: Arc::clone(&self.expected_audiences),
                scopes: Arc::clone(&self.scopes),
                now: self.now,
            },
        )
    }
}

struct RequireScopesService {
    inner: SharedService,
    service_id: Arc<str>,
    expected_audiences: Arc<[String]>,
    scopes: Arc<[String]>,
    now: fn() -> u64,
}

impl Service<ServerFnRequest, ServerFnResponse> for RequireScopesService {
    fn run(
        &mut self,
        request: ServerFnRequest,
        _serialize_error: fn(ServerFnErrorErr) -> bytes::Bytes,
    ) -> ServerFnFuture {
        let context = match verified_context_from_request(
            &request,
            &self.service_id,
            &self.expected_audiences,
            (self.now)(),
        ) {
            Ok(context) => context,
            Err(error) => return response_future(error.status()),
        };
        let Ok(principal) = context.require_principal() else {
            return response_future(StatusCode::UNAUTHORIZED);
        };
        if !self
            .scopes
            .iter()
            .all(|required| principal.scopes().binary_search(required).is_ok())
        {
            return response_future(StatusCode::FORBIDDEN);
        }
        provide_context(context.authentication.clone());
        provide_context(context);
        run_inner(Arc::clone(&self.inner), request)
    }
}

type SharedService = Arc<Mutex<BoxedService<ServerFnRequest, ServerFnResponse>>>;
type ServerFnFuture = std::pin::Pin<Box<dyn std::future::Future<Output = ServerFnResponse> + Send>>;

fn verified_context_from_request<B>(
    request: &Request<B>,
    expected_service_id: &str,
    expected_audiences: &[String],
    now: u64,
) -> Result<LeptosAuthzContext, LeptosAuthzError> {
    let verified = request
        .extensions()
        .get::<VerifiedAuthContext>()
        .ok_or(LeptosAuthzError::InvalidBoundary)?;
    LeptosAuthzContext::from_verified_at_for_audiences(
        verified,
        expected_service_id,
        expected_audiences,
        now,
    )
}

fn run_inner(inner: SharedService, request: ServerFnRequest) -> ServerFnFuture {
    Box::pin(async move {
        let future = {
            let mut inner = inner.lock().await;
            inner.run(request)
        };
        future.await
    })
}

fn response_future(status: StatusCode) -> ServerFnFuture {
    Box::pin(async move { plain_response(status) })
}

fn plain_response(status: StatusCode) -> ServerFnResponse {
    let mut response = Response::new(AxumBody::empty());
    *response.status_mut() = status;
    response.headers_mut().insert(
        http::header::CACHE_CONTROL,
        http::HeaderValue::from_static("no-store"),
    );
    response.headers_mut().insert(
        http::header::CONTENT_LENGTH,
        http::HeaderValue::from_static("0"),
    );
    if status == StatusCode::UNAUTHORIZED {
        response
            .headers_mut()
            .insert(WWW_AUTHENTICATE, http::HeaderValue::from_static("Bearer"));
    }
    response
}

fn server_fn_error(status: StatusCode, message: &'static str) -> ServerFnError {
    if let Some(sink) = use_context::<ResponseStatusSink>() {
        sink.apply(status, &safe_error_headers(status));
    }
    ServerFnError::ServerError(message.to_owned())
}

fn auth_context_server_error(_error: AuthContextError) -> ServerFnError {
    server_fn_error(
        StatusCode::SERVICE_UNAVAILABLE,
        "trusted authentication context is unavailable",
    )
}

fn safe_error_headers(status: StatusCode) -> HeaderMap {
    let mut headers = HeaderMap::new();
    headers.insert(
        http::header::CACHE_CONTROL,
        http::HeaderValue::from_static("no-store"),
    );
    if status == StatusCode::UNAUTHORIZED {
        headers.insert(WWW_AUTHENTICATE, http::HeaderValue::from_static("Bearer"));
    }
    headers
}

fn system_unix_time() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(u64::MAX, |duration| duration.as_secs())
}

fn validated_service_id(value: String) -> Result<Arc<str>, LeptosAuthzError> {
    Resource::new("service", value.clone()).map_err(invalid_contract)?;
    Ok(value.into())
}

fn validated_expected_audiences<I, S>(audiences: I) -> Result<Arc<[String]>, LeptosAuthzError>
where
    I: IntoIterator<Item = S>,
    S: Into<String>,
{
    let validated = AuthContextV1::anonymous("audience-validation", audiences)
        .map_err(|_| LeptosAuthzError::InvalidConfiguration)?;
    Ok(validated.audiences().to_vec().into())
}

fn invalid_contract(_error: ContractError) -> LeptosAuthzError {
    LeptosAuthzError::InvalidConfiguration
}

#[cfg(test)]
mod tests {
    use super::*;
    use http_body_util::BodyExt as _;
    use leptos::prelude::Owner;
    use std::sync::Mutex as StdMutex;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use wasi_authz_client::ProviderFuture;
    use wasi_authz_contract::ActionNameV1;
    use wasi_authz_testkit::{MockProvider, authenticated_request};
    use wasi_http_metadata::{
        AUTH_CONTEXT_HEADER, AuthContextV1, PrincipalV1, encode_auth_context, insert_auth_context,
    };

    #[test]
    fn require_auth_rejects_missing_and_anonymous_context() {
        let calls = Arc::new(AtomicUsize::new(0));
        let layer = RequireAuthLayer::new("orders-api").expect("valid fixture");
        let mut service = layer.layer(test_service(Arc::clone(&calls)));
        let missing = Request::new(AxumBody::from("payload"));

        let missing_response = run_service_in_owner(&mut service, missing);

        assert_eq!(missing_response.status(), StatusCode::SERVICE_UNAVAILABLE);
        let mut anonymous = Request::new(AxumBody::from("payload"));
        install_verified_extension(
            &mut anonymous,
            AuthContextV1::anonymous("orders-api", ["orders-api"]).expect("valid fixture"),
        );
        let anonymous_response = run_service_in_owner(&mut service, anonymous);
        assert_eq!(anonymous_response.status(), StatusCode::UNAUTHORIZED);
        assert_eq!(
            anonymous_response.headers().get(WWW_AUTHENTICATE),
            Some(&http::HeaderValue::from_static("Bearer"))
        );
        assert_eq!(calls.load(Ordering::SeqCst), 0);
    }

    #[test]
    fn require_auth_rejects_spoofed_duplicate_cross_service_and_expired_context() {
        let calls = Arc::new(AtomicUsize::new(0));
        let layer = RequireAuthLayer::new("orders-api")
            .expect("valid fixture")
            .with_time_source(fixed_now);
        let mut service = layer.layer(test_service(Arc::clone(&calls)));

        let mut spoofed = Request::new(AxumBody::from("payload"));
        insert_auth_context(spoofed.headers_mut(), &authenticated_context([]))
            .expect("header encodes");
        spoofed.headers_mut().insert(
            AUTHORIZATION,
            http::HeaderValue::from_static("Bearer untrusted"),
        );
        let spoofed_response = run_service_in_owner(&mut service, spoofed);
        assert_eq!(spoofed_response.status(), StatusCode::SERVICE_UNAVAILABLE);
        assert_eq!(
            spoofed_response.headers().get(http::header::CACHE_CONTROL),
            Some(&http::HeaderValue::from_static("no-store"))
        );

        let mut duplicate = Request::new(AxumBody::from("payload"));
        let encoded = encode_auth_context(&authenticated_context([])).expect("header encodes");
        duplicate
            .headers_mut()
            .append(AUTH_CONTEXT_HEADER, encoded.clone());
        duplicate.headers_mut().append(AUTH_CONTEXT_HEADER, encoded);
        assert_eq!(
            run_service_in_owner(&mut service, duplicate).status(),
            StatusCode::SERVICE_UNAVAILABLE
        );

        let mut cross_service = Request::new(AxumBody::from("payload"));
        install_verified_extension(
            &mut cross_service,
            authenticated_context_for("billing-api", [], None),
        );
        assert_eq!(
            run_service_in_owner(&mut service, cross_service).status(),
            StatusCode::SERVICE_UNAVAILABLE
        );

        let mut wrong_audience = Request::new(AxumBody::from("payload"));
        install_verified_extension(
            &mut wrong_audience,
            authenticated_context_with_audiences("orders-api", ["billing-api"]),
        );
        assert_eq!(
            run_service_in_owner(&mut service, wrong_audience).status(),
            StatusCode::UNAUTHORIZED
        );

        let mut expired = Request::new(AxumBody::from("payload"));
        install_verified_extension(
            &mut expired,
            authenticated_context_for("orders-api", [], Some(99)),
        );
        assert_eq!(
            run_service_in_owner(&mut service, expired).status(),
            StatusCode::UNAUTHORIZED
        );
        assert_eq!(calls.load(Ordering::SeqCst), 0);
    }

    #[test]
    fn require_scopes_forwards_body_without_collecting_it() {
        let calls = Arc::new(AtomicUsize::new(0));
        let layer = RequireScopesLayer::new("orders-api", ["orders.write"]).expect("valid fixture");
        let mut service = layer.layer(test_service(Arc::clone(&calls)));
        let mut request = Request::new(AxumBody::from("payload"));
        install_verified_extension(&mut request, authenticated_context(["orders.write"]));

        let response = run_service_in_owner(&mut service, request);

        assert_eq!(response.status(), StatusCode::NO_CONTENT);
        assert_eq!(calls.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn require_auth_accepts_a_distinct_configured_audience() {
        let calls = Arc::new(AtomicUsize::new(0));
        let layer = RequireAuthLayer::new("orders-api")
            .expect("valid fixture")
            .with_expected_audiences(["api://orders"])
            .expect("valid audience");
        let mut service = layer.layer(test_service(Arc::clone(&calls)));
        let mut request = Request::new(AxumBody::from("payload"));
        install_verified_extension(
            &mut request,
            authenticated_context_with_audiences("orders-api", ["api://orders"]),
        );

        let response = run_service_in_owner(&mut service, request);

        assert_eq!(response.status(), StatusCode::NO_CONTENT);
        assert_eq!(calls.load(Ordering::SeqCst), 1);
        assert!(
            RequireAuthLayer::new("orders-api")
                .expect("valid service")
                .with_expected_audiences(Vec::<String>::new())
                .is_err()
        );
    }

    #[test]
    fn require_scopes_maps_insufficient_scope_to_403() {
        let calls = Arc::new(AtomicUsize::new(0));
        let layer = RequireScopesLayer::new("orders-api", ["orders.write"]).expect("valid fixture");
        let mut service = layer.layer(test_service(Arc::clone(&calls)));
        let mut request = Request::new(AxumBody::from("payload"));
        install_verified_extension(&mut request, authenticated_context(["orders.read"]));

        let response = run_service_in_owner(&mut service, request);

        assert_eq!(response.status(), StatusCode::FORBIDDEN);
        assert_eq!(calls.load(Ordering::SeqCst), 0);
    }

    #[test]
    fn context_lifecycle_uses_leptos_request_parts() {
        let mut request = Request::new(());
        let expected = authenticated_context(["orders.read"]);
        install_verified_extension(&mut request, expected.clone());
        let (parts, ()) = request.into_parts();

        let owner = Owner::new();
        owner.with(|| {
            provide_context(parts);
            let provided = provide_auth_context().expect("context installs");
            let current = current_auth_context().expect("context is current");

            assert_eq!(provided, expected);
            assert_eq!(current, expected);
            assert!(require_principal().is_err());
        });
    }

    #[test]
    fn raw_context_provider_rejects_surviving_authorization() {
        let mut request = Request::new(());
        insert_auth_context(request.headers_mut(), &authenticated_context([]))
            .expect("header encodes");
        request.headers_mut().insert(
            AUTHORIZATION,
            http::HeaderValue::from_static("Bearer must-not-survive"),
        );
        let (parts, ()) = request.into_parts();

        Owner::new().with(|| {
            provide_context(parts);
            assert_eq!(
                provide_auth_context(),
                Err(AuthContextError::InvalidBoundary)
            );
        });
    }

    #[test]
    fn typed_context_debug_redacts_trusted_identity() {
        let context = authenticated_context([]);
        let verified = verified_context(&context);

        let debug = format!("{verified:?}");

        assert!(!debug.contains("alice"));
        assert!(!debug.contains("identity.example"));
        assert!(!debug.contains("decision-1"));
        assert!(debug.contains("[REDACTED]"));
    }

    #[test]
    fn free_authorize_maps_allow_deny_and_provider_error() {
        let context = authenticated_context([]);
        let allow = canonical_evaluation(
            &context,
            ActionNameV1::new("document.read").expect("valid fixture"),
        );
        let deny = canonical_evaluation(
            &context,
            ActionNameV1::new("document.delete").expect("valid fixture"),
        );
        let recorded = Arc::new(StdMutex::new(Vec::new()));

        Owner::new().with(|| {
            provide_context(verified_context(&context));
            let captured = Arc::clone(&recorded);
            provide_response_status_sink(ResponseStatusSink::new(move |status, headers| {
                captured
                    .lock()
                    .expect("status recorder lock")
                    .push((status, headers.clone()));
            }));

            let metadata = block_on(authorize(&MockProvider, allow)).expect("allow succeeds");
            assert_eq!(
                metadata
                    .model()
                    .map(wasi_authz_contract::ModelNameV1::as_str),
                Some("mock")
            );
            assert!(block_on(authorize(&MockProvider, deny)).is_err());
            let provider_error = canonical_evaluation(
                current_authz_context()
                    .expect("context is current")
                    .authentication(),
                ActionNameV1::new("document.read").expect("valid fixture"),
            );
            assert!(block_on(authorize(&FailingProvider, provider_error)).is_err());
        });

        let recorded = recorded.lock().expect("status recorder lock");
        assert_eq!(recorded.len(), 2);
        assert_eq!(recorded[0].0, StatusCode::FORBIDDEN);
        assert_eq!(recorded[1].0, StatusCode::SERVICE_UNAVAILABLE);
        assert_eq!(
            recorded[0].1.get(http::header::CACHE_CONTROL),
            Some(&http::HeaderValue::from_static("no-store"))
        );
    }

    #[test]
    fn free_authorize_rejects_subject_mismatch_before_provider() {
        let recorded = Arc::new(StdMutex::new(Vec::new()));
        Owner::new().with(|| {
            let context = authenticated_context([]);
            provide_context(verified_context(&context));
            let captured = Arc::clone(&recorded);
            provide_response_status_sink(ResponseStatusSink::new(move |status, _headers| {
                captured.lock().expect("status recorder lock").push(status);
            }));
            let mismatched =
                authenticated_request(ActionNameV1::new("document.read").expect("valid fixture"));

            assert!(block_on(authorize(&PanicProvider, mismatched)).is_err());
        });

        assert_eq!(
            recorded.lock().expect("status recorder lock").as_slice(),
            &[StatusCode::SERVICE_UNAVAILABLE]
        );
    }

    #[test]
    fn hybrid_authorize_should_not_call_relationship_provider_after_cedar_denies() {
        Owner::new().with(|| {
            let context = authenticated_context([]);
            provide_context(verified_context(&context));
            let evaluation = canonical_evaluation(
                &context,
                ActionNameV1::new("document.delete").expect("valid fixture"),
            );

            let result = block_on(authorize_hybrid_current(
                &MockProvider,
                &PanicProvider,
                evaluation,
            ));

            assert!(result.is_err());
        });
    }

    #[test]
    fn current_hybrid_authorize_should_build_evaluation_from_verified_subject() {
        Owner::new().with(|| {
            let context = authenticated_context([]);
            provide_context(verified_context(&context));
            let fixture =
                authenticated_request(ActionNameV1::new("document.read").expect("valid fixture"));

            let result = block_on(authorize_current_hybrid(
                &MockProvider,
                &MockProvider,
                fixture.action().clone(),
                fixture.resource().clone(),
            ));

            assert!(result.is_ok());
        });
    }

    #[test]
    fn current_relationship_authorize_should_apply_requested_consistency() {
        Owner::new().with(|| {
            let context = authenticated_context([]);
            provide_context(verified_context(&context));
            let fixture =
                authenticated_request(ActionNameV1::new("document.read").expect("valid fixture"));
            let provider = RecordingProvider::default();

            let result = block_on(authorize_current_relationship(
                &provider,
                fixture.action().clone(),
                fixture.resource().clone(),
                Consistency::FullyConsistent,
            ));

            assert!(
                result.is_ok(),
                "relationship authorization failed: {result:?}"
            );
            assert_eq!(
                provider.recorded(),
                vec![Some(Consistency::FullyConsistent)]
            );
        });
    }

    #[test]
    fn consistency_aware_hybrid_should_keep_cedar_input_provider_neutral() {
        Owner::new().with(|| {
            let context = authenticated_context([]);
            provide_context(verified_context(&context));
            let fixture =
                authenticated_request(ActionNameV1::new("document.read").expect("valid fixture"));
            let cedar = RecordingProvider::default();
            let relationship = RecordingProvider::default();

            let result = block_on(authorize_current_hybrid_with_consistency(
                &cedar,
                &relationship,
                fixture.action().clone(),
                fixture.resource().clone(),
                Consistency::FullyConsistent,
            ));

            assert!(result.is_ok(), "hybrid authorization failed: {result:?}");
            assert_eq!(cedar.recorded(), vec![None]);
            assert_eq!(
                relationship.recorded(),
                vec![Some(Consistency::FullyConsistent)]
            );
        });
    }

    fn authenticated_context<const N: usize>(scopes: [&str; N]) -> AuthContextV1 {
        authenticated_context_for("orders-api", scopes, None)
    }

    fn authenticated_context_for<const N: usize>(
        service_id: &str,
        scopes: [&str; N],
        expires_at: Option<u64>,
    ) -> AuthContextV1 {
        let principal = PrincipalV1::new("https://identity.example", "alice")
            .expect("valid fixture")
            .with_scopes(scopes)
            .expect("valid fixture")
            .with_times(Some(1), expires_at)
            .expect("valid fixture");
        AuthContextV1::authenticated(
            service_id,
            [service_id],
            principal,
            "decision-1",
            "policy-1",
        )
        .expect("valid fixture")
    }

    fn authenticated_context_with_audiences<const N: usize>(
        service_id: &str,
        audiences: [&str; N],
    ) -> AuthContextV1 {
        let principal =
            PrincipalV1::new("https://identity.example", "alice").expect("valid fixture");
        AuthContextV1::authenticated(service_id, audiences, principal, "decision-1", "policy-1")
            .expect("valid fixture")
    }

    fn canonical_evaluation(context: &AuthContextV1, action: ActionNameV1) -> AccessEvaluation {
        let fixture = authenticated_request(action);
        AccessEvaluation::new(
            subject_from_auth_context(context, context.service_id()).expect("canonical subject"),
            fixture.action().clone(),
            fixture.resource().clone(),
        )
    }

    fn verified_context(context: &AuthContextV1) -> LeptosAuthzContext {
        let mut headers = HeaderMap::new();
        insert_auth_context(&mut headers, context).expect("header encodes");
        LeptosAuthzContext::from_headers_at_for_audiences(
            &headers,
            context.service_id(),
            context.audiences(),
            fixed_now(),
        )
        .expect("context verifies")
    }

    fn install_verified_extension<B>(request: &mut Request<B>, context: AuthContextV1) {
        request
            .extensions_mut()
            .insert(VerifiedAuthContext::new(context));
    }

    fn fixed_now() -> u64 {
        100
    }

    #[derive(Debug)]
    struct FailingProvider;

    #[derive(Debug)]
    struct FailingProviderError;

    impl std::fmt::Display for FailingProviderError {
        fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            formatter.write_str("provider unavailable")
        }
    }

    impl std::error::Error for FailingProviderError {}

    impl DecisionProvider for FailingProvider {
        type Error = FailingProviderError;

        fn evaluate<'a>(
            &'a self,
            _evaluation: &'a AccessEvaluation,
        ) -> ProviderFuture<'a, Self::Error> {
            Box::pin(async { Err(FailingProviderError) })
        }
    }

    #[derive(Debug)]
    struct PanicProvider;

    impl DecisionProvider for PanicProvider {
        type Error = FailingProviderError;

        fn evaluate<'a>(
            &'a self,
            _evaluation: &'a AccessEvaluation,
        ) -> ProviderFuture<'a, Self::Error> {
            panic!("provider must not run for an untrusted subject")
        }
    }

    #[derive(Debug, Default)]
    struct RecordingProvider {
        consistency: StdMutex<Vec<Option<Consistency>>>,
    }

    impl RecordingProvider {
        fn recorded(&self) -> Vec<Option<Consistency>> {
            self.consistency
                .lock()
                .expect("consistency recorder lock")
                .clone()
        }
    }

    impl DecisionProvider for RecordingProvider {
        type Error = wasi_authz_testkit::MockProviderError;

        fn evaluate<'a>(
            &'a self,
            evaluation: &'a AccessEvaluation,
        ) -> ProviderFuture<'a, Self::Error> {
            Box::pin(async move {
                self.consistency
                    .lock()
                    .expect("consistency recorder lock")
                    .push(
                        evaluation
                            .context()
                            .and_then(ContextV1::consistency)
                            .cloned(),
                    );
                MockProvider.evaluate(evaluation).await
            })
        }
    }

    fn test_service(calls: Arc<AtomicUsize>) -> BoxedService<ServerFnRequest, ServerFnResponse> {
        BoxedService::new(|_| bytes::Bytes::new(), BodyCheckingService { calls })
    }

    struct BodyCheckingService {
        calls: Arc<AtomicUsize>,
    }

    impl Service<ServerFnRequest, ServerFnResponse> for BodyCheckingService {
        fn run(
            &mut self,
            request: ServerFnRequest,
            _serialize_error: fn(ServerFnErrorErr) -> bytes::Bytes,
        ) -> ServerFnFuture {
            let calls = Arc::clone(&self.calls);
            Box::pin(async move {
                let body = request
                    .into_body()
                    .collect()
                    .await
                    .expect("fixture body collects")
                    .to_bytes();
                assert_eq!(body, "payload");
                let context = current_authz_context().expect("typed context is installed");
                assert!(context.subject().is_authenticated());
                calls.fetch_add(1, Ordering::SeqCst);
                plain_response(StatusCode::NO_CONTENT)
            })
        }
    }

    fn run_service_in_owner(
        service: &mut BoxedService<ServerFnRequest, ServerFnResponse>,
        request: ServerFnRequest,
    ) -> ServerFnResponse {
        Owner::new().with(|| block_on(service.run(request)))
    }

    fn block_on<F>(future: F) -> F::Output
    where
        F: std::future::Future,
    {
        use std::task::{Context, Poll, Waker};

        let waker = Waker::noop();
        let mut context = Context::from_waker(waker);
        let mut future = Box::pin(future);
        loop {
            match future.as_mut().poll(&mut context) {
                Poll::Ready(output) => return output,
                Poll::Pending => std::thread::yield_now(),
            }
        }
    }
}
