#!/usr/bin/env python3
"""Generate the machine-readable companion surface manifest.

A downstream consumer such as `leptos_wasi` depends on this repository through
local path dependencies spanning two workspaces at two different versions. The
generated `companion.toml` is the single record of that surface: every crate a
consumer may depend on, every built component, and the release-bundle evidence
paths a consumer pins. It is derived from `cargo metadata`, so a rename, a
version bump, or a dropped crate fails the build instead of silently drifting.
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys


SCHEMA = 1

# Crates a downstream consumer is supported in depending on, and the workspace
# each is resolved from. Adding a crate here is a deliberate widening of the
# supported companion surface.
COMPANION_CRATES = [
    ("leptos-wasi-authz", "crates/leptos-wasi-authz", "wasi-auth"),
    ("wasi-authz-cedar", "crates/wasi-authz-cedar", "wasi-auth"),
    ("wasi-authz-client", "crates/wasi-authz-client", "wasi-auth"),
    ("wasi-authz-contract", "crates/wasi-authz-contract", "wasi-auth"),
    ("wasi-authz-spicedb", "crates/wasi-authz-spicedb", "wasi-auth"),
    (
        "wasi-http-authn",
        "legacy/wasi-http-middleware/crates/authn",
        "wasi-http-middleware",
    ),
]

# Built component artifacts. The source directory and the artifact name differ
# for the HTTP PEP on purpose; both names are recorded so a consumer never has
# to infer one from the other.
COMPONENTS = [
    ("authz-http-pep", "wasi-authz-http-pep", "components/http-pep", "http-pep"),
    (
        "cedar-pdp",
        "wasi-authz-cedar-pdp-component",
        "components/cedar-pdp",
        "cedar-pdp",
    ),
    (
        "spicedb-pdp",
        "wasi-authz-spicedb-pdp-component",
        "components/spicedb-pdp",
        "spicedb-pdp",
    ),
]

# Release-bundle evidence, relative to this repository root. These are the
# exact paths `scripts/dry-run-supply-chain.sh` writes.
BUNDLE_EVIDENCE = [
    ("checksum_manifest", "artifacts/RELEASE-SHA256SUMS"),
    ("provenance", "artifacts/provenance.intoto.json"),
    ("oci_manifest", "reports/supply-chain/manifest.json"),
    (
        "provenance_signature",
        "reports/supply-chain/provenance.intoto.json.sigstore.json",
    ),
    ("manifest_signature", "reports/supply-chain/manifest.json.sigstore.json"),
    ("signing_key", "reports/supply-chain/cosign.pub"),
]

ARTIFACT_NAME = "wasi-authz"


def metadata(manifest: pathlib.Path) -> dict[str, dict]:
    """Return resolved packages for one workspace, keyed by package name."""
    raw = subprocess.run(
        [
            "cargo",
            "metadata",
            "--locked",
            "--no-deps",
            "--format-version",
            "1",
            "--manifest-path",
            str(manifest),
        ],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return {package["name"]: package for package in json.loads(raw)["packages"]}


def publishable(package: dict) -> bool:
    """Return whether Cargo would allow publishing this package."""
    return package.get("publish") != []


def quote(value: str) -> str:
    """Return one TOML basic string."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    """Write `companion.toml` derived from both workspace manifests."""
    if len(sys.argv) != 3:
        print(
            "usage: generate-companion-manifest.py REPOSITORY OUTPUT",
            file=sys.stderr,
        )
        return 2
    repository = pathlib.Path(sys.argv[1]).resolve()
    output = pathlib.Path(sys.argv[2])

    workspaces = {
        "wasi-auth": metadata(repository / "Cargo.toml"),
        "wasi-http-middleware": metadata(
            repository / "legacy/wasi-http-middleware/Cargo.toml"
        ),
    }

    release = workspaces["wasi-auth"]["wasi-auth"]["version"]

    lines = [
        "# Generated by scripts/generate-companion-manifest.sh. Do not edit by hand.",
        "#",
        "# This is the supported companion surface of this repository: the crates a",
        "# downstream consumer may path-depend on, the components a release builds,",
        "# and the evidence files a consumer pins. Regenerate after any version or",
        "# packaging change; CI requires the tracked copy to match.",
        f"schema = {SCHEMA}",
        "",
        "[release]",
        "name = " + quote("wasi-auth"),
        "version = " + quote(release),
        "",
        "[artifact]",
        "name = " + quote(ARTIFACT_NAME),
        "version = " + quote(release),
        "components = ["
        + ", ".join(quote(component) for component, *_ in COMPONENTS)
        + "]",
    ]
    for key, path in BUNDLE_EVIDENCE:
        lines.append(f"{key} = " + quote(path))

    for name, path, workspace in COMPANION_CRATES:
        packages = workspaces[workspace]
        if name not in packages:
            print(
                f"error: companion crate is missing from {workspace}: {name}",
                file=sys.stderr,
            )
            return 1
        package = packages[name]
        resolved = pathlib.Path(package["manifest_path"]).parent
        expected = repository / path
        if resolved != expected:
            print(
                f"error: companion crate {name} moved: expected {expected}, "
                f"found {resolved}",
                file=sys.stderr,
            )
            return 1
        lines.extend(
            [
                "",
                "[[crate]]",
                "package = " + quote(name),
                "path = " + quote(path),
                "version = " + quote(package["version"]),
                "workspace = " + quote(workspace),
                "publish = " + ("true" if publishable(package) else "false"),
            ]
        )

    for component, package_name, source_path, wit_stem in COMPONENTS:
        packages = workspaces["wasi-auth"]
        if package_name not in packages:
            print(
                f"error: component package is missing: {package_name}",
                file=sys.stderr,
            )
            return 1
        lines.extend(
            [
                "",
                "[[component]]",
                "component = " + quote(component),
                "package = " + quote(package_name),
                "source_path = " + quote(source_path),
                "path = " + quote(f"components/{component}.wasm"),
                "sbom = " + quote(f"artifacts/sbom/{package_name}.cdx.json"),
                "wit = " + quote(f"reports/wit/{wit_stem}.wit"),
            ]
        )

    output.write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
